"""modify article model, add timestamp index

Revision ID: 1a6f4606c370
Revises: f8a126c0c3d
Create Date: 2016-06-10 09:41:40.270000

"""

# revision identifiers, used by Alembic.
revision = '1a6f4606c370'
down_revision = 'f8a126c0c3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_date'), 'articles', ['date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_date'), table_name='articles')
    ### end Alembic commands ###
