"""modify prototype model

Revision ID: 2767d5c9a7ad
Revises: 2e225df00b00
Create Date: 2016-06-07 17:20:30.317000

"""

# revision identifiers, used by Alembic.
revision = '2767d5c9a7ad'
down_revision = '2e225df00b00'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prototypes', sa.Column('author', sa.String(length=64), nullable=True))
    op.add_column('prototypes', sa.Column('dynasty', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_prototypes_author'), 'prototypes', ['author'], unique=False)
    op.drop_column('prototypes', 'info')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prototypes', sa.Column('info', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_prototypes_author'), table_name='prototypes')
    op.drop_column('prototypes', 'dynasty')
    op.drop_column('prototypes', 'author')
    ### end Alembic commands ###
