"""enhance prototype model

Revision ID: 2e225df00b00
Revises: 14051817d850
Create Date: 2016-06-05 20:43:24.420000

"""

# revision identifiers, used by Alembic.
revision = '2e225df00b00'
down_revision = '14051817d850'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prototypes', sa.Column('body_hash', sa.String(length=128), nullable=True))
    op.add_column('prototypes', sa.Column('info', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_prototypes_body_hash'), 'prototypes', ['body_hash'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prototypes_body_hash'), table_name='prototypes')
    op.drop_column('prototypes', 'info')
    op.drop_column('prototypes', 'body_hash')
    ### end Alembic commands ###
