"""add user confirm func

Revision ID: 397b1e1095a2
Revises: 3606ef604a9c
Create Date: 2016-06-04 17:25:48.484000

"""

# revision identifiers, used by Alembic.
revision = '397b1e1095a2'
down_revision = '3606ef604a9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
