"""create article model

Revision ID: 480598e7bb7e
Revises: 2b79b78ff945
Create Date: 2016-06-05 16:26:28.800000

"""

# revision identifiers, used by Alembic.
revision = '480598e7bb7e'
down_revision = '2b79b78ff945'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
