"""modify article model, add timestamp default

Revision ID: f8a126c0c3d
Revises: 2767d5c9a7ad
Create Date: 2016-06-10 09:40:56.483000

"""

# revision identifiers, used by Alembic.
revision = 'f8a126c0c3d'
down_revision = '2767d5c9a7ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
